#! /bin/bash
echo "deb https://packages-cf.termux.dev/apt/termux-main stable main" > $PREFIX/etc/apt/sources.list

pkg update -y

DEBIAN_FRONTEND=noninteractive \
pkg upgrade -y -o Dpkg::Options::="--force-confold"

pkg install -y python mpv termux-api

termux-setup-storage
APPDIR=~/storage/shared/Droido-Player-Data
mkdir -p "$APPDIR"
