#! /bin/bash
echo "deb https://packages-cf.termux.dev/apt/termux-main stable main" > $PREFIX/etc/apt/sources.list

pkg update -y
pkg upgrade -y
pkg install -y python termux-api

termux-setup-storage
APPDIR=~/storage/shared/Droido-Player-Data
mkdir -p "$APPDIR"
