#! /bin/bash
echo "deb https://packages-cf.termux.dev/apt/termux-main stable main" > $PREFIX/etc/apt/sources.list

pkg update -y

DEBIAN_FRONTEND=noninteractive \
pkg upgrade -y -o Dpkg::Options::="--force-confold"

pkg install -y python mpv termux-api ffmpeg
pkg install -y yt-dlp || python3 -m pip install --user yt-dlp

termux-setup-storage
APPDIR=~/storage/shared/Droido-Player-Data
mkdir -p "$APPDIR"

SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cp "$SETUP_DIR/run" ~/
chmod +x ~/run
